name: frontend
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  location: ^5.0.3
  flutter_local_notifications: ^16.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/faq_icon.png
    - assets/fire_icon.png
    - assets/stats_icon.png
    - assets/recent_wildfires.png
    - assets/hectares_burned.png
  fonts:
    - family: Dela Gothic One,
      fonts:
        - asset: assets/fonts/DelaGothicOne-Regular.ttf
